# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker-Coq Action
      - uses: coq-community/docker-coq-action@v1.2.4
        with:
          # The path of the .opam file (or a directory), relative to the repo root.
          opam_file: stlc/stlc.opam
          # "8.X", "latest", or "dev".
          coq_version: 8.14 # optional, default is latest
          # "minimal", "4.XX", or "4.XX-flambda", see https://github.com/coq-community/docker-coq/wiki#supported-tags

          # Customizable script to install the opam dependencies.
          install: |
            opam pin add -n -y -k path $PACKAGE $WORKDIR
            opam update -y
            opam install -y -j 2 $PACKAGE --deps-only

          script: |
            opam install -y -v -j 2 $PACKAGE
            opam list

          # Customizable script run to uninstall the opam package(s).
          uninstall: |
            opam remove $PACKAGE

          # The main script run in the container; may be overridden.
          custom_script: |
            {{install}}
            {{after_install}}
            {{before_script}}
            {{script}}
            {{after_script}}
            {{uninstall}}
